### ISSUE TITLE
ETA on 1.20.6

### ISSUE THREAD

**Issue by caitlynrw** [Strobel273/InventiveInventory#22]
Hiya, just wondering if there's an ETA on a build for 1.20.6

**Comment by Strobel273** [comment]
Hey, thank you for your message.

We will add version compatibilty for 1.20.6 and others as soon as possible now.
Stay tuned for the release in one or two days.

Your Inventive Inventory Team

**Comment by LU-XD** [comment]
Hey there,

unfortunately, due to some changes in the Minecraft source code that affect our mod, 
we have to postpone the release for a few days.

Your Inventive Inventory Team

**Comment by LU-XD** [comment]
Hey there,

we have uploaded the new version to Modrinth.
If you encounter any bugs, please let us know.

Your Inventive Inventory Team
