### ISSUE TITLE
Middle Mouse Button Sort

### ISSUE THREAD

**Issue by ShayBox** [Strobel273/InventiveInventory#24]
Middle Mouse Button Sort

**Comment by Strobel273** [comment]
Hey there,
can you please specify what you mean by that? 
Do you want to request a feature or do you expereince a problem with a keybinding?

A more detailed description would help us tackle the problem more efficient.
 
Thank you,
Your Inventive Inventory Team

**Comment by ShayBox** [comment]
Is there a way to sort with middle mouse button, or could that be added? I'm not able to bind the sort key to a mouse button in the settings, but I'm used to using MMB because of InventoryTweaks/InventorySorter/MouseWheelie, but I like the ability to lock slots from this mod.

**Comment by LU-XD** [comment]
Hey there,
thank you for your description.

We will look into this in the next few days.
Stay tuned for updates.

Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey there,
we have added the functionality to use mouse buttons as keybinds now and fixed a few other bugs we have noticed on the run.
The updated versions are now online on Modrinth.

If you notice any other bugs or have any other feature suggestions, feel free to let us know.
Thank you again for your report and have fun with our mod.

Your Inventive Inventory Team
