### ISSUE TITLE
New FEATURE: Sort after item-type

### ISSUE THREAD

**Issue by Jultk** [Strobel273/InventiveInventory#29]
**Mod Version & Minecraft Version**
0.4.3 - Minecraft 1.21

**Describe the Feature**
An config option to change the sorting from default(only item name) to item-type.
would be much more intuitive, because normally you want for example all your ingots next to each other.

| Slot 1     | Slot 2      | Slot 3               | Slot 4
Gold (64) | Gold (40) | Redstone (12) | lime stone (5)

instead of:

| Slot 1     | Slot 2      | Slot 3               | Slot 4
Gold (64) | Gold (40) | lime stone (5)  | Redstone (12) 

let me know if you could implement such an option :)

best regards, Julian

**Comment by LU-XD** [comment]
Hey there,

we really like the idea and will be working on this new feature from now on.
Thanks for your idea and stay tuned for the update.

Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey Julian,
as it appears is your feature request more of a big deal than it seemed at the first glance.
Actually before tackling this we have planned to overhaul our mod architecture to develop more efficiently in the future and to be able to implement such features faster and better.

After this process we want to release a massive update for our sorting feature in general which will include additional functions we already had in mind.

Sorry for the delay but we hope you understand and you can look forward to a new and rethought version of our mod.

Your Inventive Inventory Team

**Comment by Jultk** [comment]
Hello Strobel273,

thanks four your quick response on my suggested feature.

---

I took a quick look at the code out of curiosity and would suggest sorting by item ID for the feature, as these are naturally ordered by item types: diamonds: 264, iron_ingot: 265...

Analogous to:

```java
private static List<Integer> getSortedSlots(InventorySlots inventorySlots, ScreenHandler screenHandler) {
        return inventorySlots.stream()
                .filter(slot -> !screenHandler.getSlot(slot).getStack().isEmpty())
                .sorted(Comparator.comparing((Integer slot) -> screenHandler.getSlot(slot).getStack().getName().getString())
                        .thenComparing(slot -> screenHandler.getSlot(slot).getStack().getCount(), Comparator.reverseOrder()))
                .toList();
    }
```

the following code or something similar could be used in `Sorter.java`:

```java
private static List<Integer> getSortedSlots(InventorySlots inventorySlots, ScreenHandler screenHandler) {
    return inventorySlots.stream()
            .filter(slot -> !screenHandler.getSlot(slot).getStack().isEmpty())
            .sorted(Comparator.comparing((Integer slot) -> Item.getRawId(screenHandler.getSlot(slot).getStack().getItem())))
            .toList();
}
```

If you have already thought of a solution based on this model and it is not so easy to implement, I understand your  decision!


Best regards,

Julian

**Comment by Jultk** [comment]
Update:

I cloned the project and changed the code like above. It worked just fine!

important: Add the import for `Item`for it to work -> `import net.minecraft.item.Item;`

**Comment by Strobel273** [comment]
Hey Jullian,
thank you for your suggestion.

We have already thought about using minecraft's categories as a medium for sorting. This approach will work for a couple scenarios just fine, but there are some problems with that. For example will a dropper get sorted between redstone dust and other ores like iron and gold. 
We want to take the sorting mechanism to the next level where the items can also be sorted contextual related.

But you're absolutely right. I think we will upload a new version that includes your suggested behavior as a bridge to our new system, as well as some bug fixes that are ready for release, before dealing with our official release version.

Thank you again,
Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey again,
the new versions including the new sorting type are now online.

Have fun,
Your Inventive Inventory Team
