### ISSUE TITLE
Auto sorting when hovering over the last slot of a container's inventory sorts the player's inventory instead.

### ISSUE THREAD

**Issue by mathias-wb** [Strobel273/InventiveInventory#30]
**Mod Version & Minecraft Version**
Inventive Inventory 0.4.3 for Minecraft Fabric 1.20.6

**Describe the bug**
When hovering the cursor over the last slot in an opened container's inventory GUI (single chest-sized or double chest-sized) and pressing the key to sort inventory, the player's inventory gets sorted instead of the container's.

**To Reproduce**
1. Open any container.
2. Hover the cursor over the last slot of the container's inventory.
3. Press the sort inventory key.
4. See error.

**Expected behavior**
Doing this should sort the container's inventory, not the player's.

**Additional context**
I also use other inventory utility mods like Mouse Tweaks, Chest Tracker, EMI, Smooth Scroll, etc. 
That being said, none of those have the functionality to sort inventories so I think it's unlikely that they're the reason for this bug.
I've tested on single chests, double chests, and barrels, all of which have the same issue.

**Comment by Strobel273** [comment]
Hey Mathias,
thank you very much for your report.

We were able to reproduce the problem and are working on a solution. 
A new version will be available shortly.

Thank you and have a nice day,
Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey again,
the new versions including the fixes are now online.
Additionally, we introduced a new sorting type.

Have fun,
Your Inventive Inventory Team
