### ISSUE TITLE
Inverted refill logic bug

### ISSUE THREAD

**Issue by Pongpaks0** [Strobel273/InventiveInventory#36]
**Mod Version & Minecraft Version**
0.4.5 & 1.20.6

**Describe the bug**
When moving item from hotbar to inventory then pressing right click, the item is returned to the hotbar

**To Reproduce**
1. Set Refill mode to `Inverted`
2. Have an item in right hand
3. Move the item to an inventory slot
4. (Without changing the hotbar slot) Right click

**Expected behavior**
The item does not get refilled

**Comment by Strobel273** [comment]
Hey Pongpaks0,
thank you a lot for your report.

We were able to reproduce the issue and are in the process of fixing it.
You can expect a new updated version soon on Modrinth.

Thank you again,
Your Inventive Inventory Team

**Comment by Strobel273** [comment]
Hey there,
your reported bug should now be fixed and the new versions were uploaded to Modrinth.

If you experience any other issues, please let us know.

Have fun,
Your Inventive Inventory
