### ISSUE TITLE
Creative Mode Loses Inventory and Locked Slots Cannot Be Changed

### ISSUE THREAD

**Issue by SinsOfVirtue** [Strobel273/InventiveInventory#38]
**Mod Version & Minecraft Version** 
Mod version 0.4.6, Minecraft 1.21 on a Realms server.

**Describe the bug**
Pressed R to sort my inventory while in Creative mode and most of my inventory disappeared in the process. I also had a slot locked and couldn't toggle it back off while in Creative. It did sort what few items it left, though!

**Expected behavior**
For inventory to only be sorted and for locked slots to still allow toggling.

**Comment by Strobel273** [comment]
Hey there,
thank you for your report.

We are aware of major issues regarding the creative mode.  We warned about using the mod in creative on our Modrinth page as there are many problems that aren't that easy to solve and require to understand the weird handling Mojang implemented there. Such fixes have been postponed to the future and we won't deal with them before we are happy with our mod in survival mode as this is our priority.
Therefore, using this mod in creative is not recommended and we will most likely disable the functionality there for now in our next update.

Thank you for your patience,
Your Inventive Inventory Team
